opendata-mvcr/mission-control

- src/app/components/Navigation.tsx
- src/app/reducers/snackbar.ts
- Fixed console errors due to invalid navigation tab selection
- Fixed Snackbar reducer
> Fixed navigation tabs and snackbar

- src/app/utils/ajax.ts
- src/id/actions.ts
- src/id/components/EditProfile.tsx
- src/id/constants.tsx
- src/id/epics.ts
- src/id/reducers.ts
- src/id/routes.ts
- src/id/translations/cs.json
- src/id/types.ts
Resolves #3 
Currently there is an issue with API that needs to be resolved before this solution works:
https://github.com/opendata-mvcr/sgov/issues/11
> Added user profile editing

- src/id/actions.ts
- src/id/components/ChangePassword.tsx
- src/id/epics.ts
- src/id/reducers.ts
- src/id/routes.ts
- src/id/translations/cs.json
- src/id/types.ts
> Added option to change password

- src/app/epics/app.ts
- src/app/utils/epic.ts
- src/id/epics.ts
- src/users/epics.ts
- src/workspaces/epics.ts
Added two RxJS operators:
- ofSafeType
- mapError
> Refactored error handling in epics

- src/app/hooks/useDispatchAction.ts
- src/app/utils/ajax.ts
- src/app/utils/uri.ts
- src/app/vocabulary.ts
- src/id/constants.tsx
- src/id/selectors.ts
- src/users/actions.ts
- src/users/api.ts
- src/users/components/UsersTable.tsx
- src/users/constants.ts
- src/users/epics.ts
- src/users/reducers.ts
- src/users/selectors.ts
- src/users/translations/cs.json
- src/users/types.ts
> Added feature to deactivate and activate users

- src/id/translations/cs.json
> Fixed translation keys for editing user pofile

- src/id/components/PasswordTextField.tsx
> Modified PasswordTextField to ignore tab on eye icon

- src/app/utils/epic.ts
- src/id/epics.ts
> Fixed profile page not being refreshed after user information changed

- netlify.toml
> Added default URL redirect to index.html

- src/tools.json
- src/workspaces/actions.ts
- src/workspaces/components/Tools.tsx
- src/workspaces/components/WorkspacesTable.tsx
- src/workspaces/reducers.ts
- src/workspaces/selectors.ts
- src/workspaces/translations/cs.json
- src/workspaces/types.ts
> [#29] actions for opening tools from workspace list

- src/app/vocabulary.ts
- src/id/reducers.ts
- src/id/selectors.ts
- src/id/types.ts
- src/users/selectors.ts
- src/users/types.ts
Fixes due to changes in API contract
Resolves #34.
> [#34] Migrated users to a new ontology and API

- src/workspaces/actions.ts
- src/workspaces/api.ts
- src/workspaces/components/PublishWorkspaceDialog.tsx
- src/workspaces/components/WorkspaceDangerZone.tsx
- src/workspaces/epics.ts
- src/workspaces/reducers.ts
- src/workspaces/selectors.ts
- src/workspaces/translations/cs.json
- src/workspaces/types.ts
This is a follow up to the previous PR with some new features.
After a workspace is published, the user is presented with a clickable GitHub PR URL directly in the application.
Resolves #41
> [#41] Publishing workspace v2

- src/workspaces/actions.ts
- src/workspaces/components/AddVocabularyForm.tsx
- src/workspaces/epics.ts
- src/workspaces/selectors.ts
- src/workspaces/types.ts
`uri` -> `basedOnVocabularyVersion`
> Updated vocabulary model to comply with server

- src/app/utils/formatDate.ts
> [#44] Last modification date includes time

- src/app/utils/epic.ts
- src/workspaces/actions.ts
- src/workspaces/epics.ts
- src/workspaces/translations/cs.json
- src/workspaces/translations/en.json
> [#68] Improved error message when adding an editable vocabulary

- src/app/config.ts
- src/app/utils/getIdFromResponse.ts
- src/app/utils/getIdFromUri.ts
- src/workspaces/actions.ts
- src/workspaces/components/AddVocabularyForm.tsx
- src/workspaces/epics.ts
- src/workspaces/types.ts
Resolves #49.
When a new workspace is created, a subsequent API call is made to add a V-SGoV vocabulary to the workspace. The IRI is configurable.
> [#49] V-SGoV added to new workspace by default

- src/workspaces/components/AddVocabularyForm.tsx
> [#76] Fixed creating a new vocabulary within a workspace

- src/workspaces/components/Tools.tsx
> [#78] Fixed link click event propagation

- src/app/translations/cs.json
- src/app/translations/en.json
- src/workspaces/components/AddVocabularyForm.tsx
- src/workspaces/components/Tools.tsx
- src/workspaces/components/WorkspaceActions.tsx
Resolves #86 
Resolves #90 
Resolves #81
> [#86,#90,#81] Improvements

- .env
- .env.development
- src/app/variables.ts
This is an attempt to fix Netlify URL configuration so that authentication over Keycloak works in production.
> Fixed Netlify URL configuration

- .env
- .env.development
- src/app/variables.ts
Hopefully fixed for good this time...
> Fixed Netlify URL configuration again

- package-lock.json
- package.json
- src/components/vocabularies/AddVocabularyForm.tsx
- src/components/vocabularies/CreateVocabularyForm.tsx
- src/components/vocabularies/ImportVocabularyForm.tsx
- src/utils/removeDiacritics.ts
Resolves #108 
I replaced the trivial regexp-based text search with https://github.com/nextapps-de/flexsearch library for some extra full-text goodness. The new solution ignores diacritics, case and is typo-tolerant.
> [#108] Added better full-text search engine

- public/oidc-dispatch-redirect.html
- public/oidc-signin-callback.html
- public/oidc-silent-callback.html
- src/app/variables.ts
- src/components/Auth.tsx
This is a RFC / attempt to add support for authentication on Netlify deploy previews without compromising security.
> [#112] Enable Keycloak authentication on Netlify deploy previews

- package-lock.json
- package.json
- src/components/App.tsx
- src/components/Title.tsx
- src/components/workspaces/WorkspaceName.tsx
- src/components/workspaces/Workspaces.tsx
> [#107] Improved web page title

- .env
- src/app/variables.ts
- src/components/Header.tsx
- src/components/Help.tsx
- src/i18n/common.cs.json
- src/i18n/common.en.json
> [#115] Added issue tracker links

- src/app/vocabularyTypes.json
- src/components/form/Checkbox.tsx
- src/components/vocabularies/CreateVocabularyForm.tsx
- src/i18n/vocabularies.cs.json
- src/i18n/vocabularies.en.json
> [#137] Pre-fill default vocabulary IRI

- src/app/routes.ts
- src/components/workspaces/MyWorkspaces.tsx
- src/components/workspaces/Workspace.tsx
- src/components/workspaces/WorkspacesTable.tsx
- src/data/workspaces.ts
- src/i18n/workspaces.cs.json
- src/i18n/workspaces.en.json
Notes:
- There is new default "My Workspaces" view containing only current user's workspaces
- There is a link at the bottom of the "My Workspaces" page leading to all workspaces
- All workspaces are still accessible
- Link back from workspace detail goes to "My Workspaces"
- This is obviously a temporary and dirty solution until we discuss and implement proper authorization
- Feedback / change requests welcome
Resolves #145.
> [#145] Added default My Workspaces view

- src/components/DataTable.tsx
- src/i18n/common.cs.json
- src/i18n/common.en.json
> [#141] Added missing localization when a data table has no records

- src/@types/users.ts
- src/components/users/Gravatar.tsx
- src/components/users/UserChip.tsx
- src/components/workspaces/WorkspacesTable.tsx
- src/data/workspaces.ts
Resolves #147.
Changes:
- User ID used for matching authenticated user and a user in data
- Gravatar changed to user initials in most cases
> [#147] Fixed My Workspaces list

- src/components/DataTable.tsx
- src/components/workspaces/WorkspacesTable.tsx
- src/data/workspaces.ts
> [#152] Fixed workspace list reload after deleting a workspace

- src/components/workspaces/PublishWorkspaceDialog.tsx
> [#162] Fixed publish action operation

- src/app/vocabularyTypes.json
- src/components/vocabularies/VocabulariesDependencies.tsx
> [#167] Improved vocabulary dependencies view

- package-lock.json
- package.json
- src/app/router.ts
- src/components/i18n.tsx
- src/components/vocabularies/ImportVocabularyForm.tsx
- src/components/vocabularies/VocabulariesTable.tsx
- src/components/vocabularies/VocabularyActions.tsx
- src/data/vocabularies.ts
- src/utils/i18n.ts
> [#172] Updated Prettier to v2.3 and reformatted code

- src/app/vocabularyTypes.json
- src/components/vocabularies/CreateVocabularyForm.tsx
> [#177] Fixed legislative dictionary default IRI format

- src/components/Router.tsx
> [#188] Fixed blank page after URL refresh

- src/components/Errors.tsx
- src/components/Header.tsx
- src/components/Router.tsx
> [#135] Link to home in header and error pages

- src/@types/workspaces.ts
- src/data/vocabularies.ts
> [#207] changing basedOnVocabularyVersion to basedOnVersion

- src/components/workspaces/WorkspaceActions.tsx
> [#196] Enable edit buttons after adding a vocabulary to workspace

- src/components/workspaces/PublishWorkspaceDialog.tsx
- src/i18n/workspaces.cs.json
- src/i18n/workspaces.en.json
> [#210] Added workspace delete prompt after publishing

- src/app/variables.ts
- src/components/workspaces/WorkspaceActions.tsx
> [#213] Added support for demo instance

- src/components/vocabularies/ImportVocabularyForm.tsx
- src/i18n/vocabularies.cs.json
- src/i18n/vocabularies.en.json
> [#214] Enable adding one vocabulary to multiple workspaces

- package-lock.json
- package.json
> [#221] Restored previous version of React Hook Form library

- src/data/vocabularies.ts
> [HOTFIX] Workaround for importing vocabularies with diagrams

- src/data/api.ts
> [#229] Fixed create vocabulary request URL

- src/data/vocabularies.ts
> [HOTFIX REVERT] Workaround for importing vocabularies with diagrams

- .vscode/settings.json
- src/@types/workspaces.ts
- src/components/vocabularies/DeleteVocabularyForm.tsx
- src/data/vocabularies.ts
- src/utils/ajax.ts
Related to this change in SGoV API: https://github.com/opendata-mvcr/sgov/pull/150
> Fixed vocabulary delete API endpoint request

- public/index.html
If this is not going to work, the server configuration must be changed.
> Disable caching
